### ISSUE TITLE
导入出错

### ISSUE THREAD

**Issue by wenha** [MewX/light-novel-library_Wenku8_Android#10]
你好，我把这个导入到as中，一直报错，加载gradle，我用迅雷下好的gradle塞到.gradle文件夹下，还是不行，能不能帮我远程看一下啊？谢谢了

**Comment by MewX** [comment]
报的什么错？请把完整日志贴上来。

这个项目我不维护了，而且我相信运行不起来一定是你没掌握使用gradle的正确姿势，多学习学习吧

**Comment by wenha** [comment]
恩恩，好的，我再看看，非常感谢！

**Comment by wenha** [comment]
大神，我运行出来了，但是在主界面“最近更新”一直显示“数据解析失败........"啊

**Comment by MewX** [comment]
恭喜，服务器不返回数据了，你搜索小说试试

**Comment by wenha** [comment]
不行，搜不出来

**Comment by MewX** [comment]
那你登录后再试试，可能服务端做了调整
