### ISSUE TITLE
新版本无法换阅读背景

### ISSUE THREAD

**Issue by Mr-zgf** [MewX/light-novel-library_Wenku8_Android#101]
使用自定义背景图片无法在文件夹里面见到背景图片，1.13版本确认没这个问题

**Comment by Mr-zgf** [comment]
![Screenshot_20230418140302_1](https://user-images.githubusercontent.com/30373670/232685862-7c21512c-44a0-4c2c-a5b2-2f0bcf6d13e8.jpg)
![Screenshot_20230418140217](https://user-images.githubusercontent.com/30373670/232685877-3a61cd12-cc7e-4da2-9a0e-9446014018c8.jpg)

**Comment by MewX** [comment]
这个在v1.17之后应该已经修复了。感谢报bug！
