### ISSUE TITLE
第一章加入封面

### ISSUE THREAD

**Issue by jimdaxu** [MewX/light-novel-library_Wenku8_Android#11]
请问一下怎么在第一章加入一个封面啊／

**Comment by MewX** [comment]
你指的是第一页加入封面？

**Comment by jimdaxu** [comment]
是啊。

**Comment by MewX** [comment]
这个和数据源有关，如果需要在第一章加入封面，直接在数据最前面放一张图片，这样图片就会出现在第一页了。

目前app还不能一页显示多张图片、以及图文混排。
