### ISSUE TITLE
不加廣告，這個app不會倒閉嗎？

### ISSUE THREAD

**Issue by Ciallo3428407306** [MewX/light-novel-library_Wenku8_Android#111]
迷糊輕小說，親小說的墳頭草已經三丈高了。

**Comment by MewX** [comment]
会啊，已经倒闭了

**Comment by mqnu00** [comment]
> 会啊，已经倒闭了

请问这个**正在更新**页面的这几个数据是爬虫爬取到的吗？我想知道获取的方法😄
![cf99920e56441e9b3ebb063c6df57592](https://github.com/MewX/light-novel-library_Wenku8_Android/assets/108623923/56bb3876-49a9-47d2-9a08-e0bfc17dc05a)

**Comment by mqnu00** [comment]
> 会啊，已经倒闭了

我看到了action=book&do=meta&aid=1306&t=0这个api，但是没找到请求的网址

**Comment by mqnu00** [comment]
> > 会啊，已经倒闭了
> 
> 我看到了action=book&do=meta&aid=1306&t=0这个api，但是没找到请求的网址

![image](https://github.com/MewX/light-novel-library_Wenku8_Android/assets/108623923/0cb20d6b-98b6-420d-a8b9-024f728398bb)
给我扒出来了😄
