### ISSUE TITLE
Need https://wenku8-relay.mewx.org/

### ISSUE THREAD

**Issue by canomi** [MewX/light-novel-library_Wenku8_Android#113]
Hi there,
Could you share with me the way to create results from https://wenku8-relay.mewx.org/.
I used this code to read the novel on my website, but I don't know how to create the response from https://wenku8-relay.mewx.org/
Thank you in advance!

**Comment by MewX** [comment]
It's simply a cache service hosted on CloudFlare Pages.

The results are exactly the same from the wenku8 API. I believe you can find examples in the API class. :-)

**Comment by canomi** [comment]
Thank you for your response. I'll try.
I hope you're doing well, I'm happy to donate to this project, please let me know if I can.
Best regards

**Comment by MewX** [comment]
Thanks for your kindness! :D I don't need donations at the moment. Let's keep this project purely free for now.

**Comment by canomi** [comment]
> It's simply a cache service hosted on CloudFlare Pages.
> 
> The results are exactly the same from the wenku8 API. I believe you can find examples in the API class. :-)

I tried to use the same URL for BASE_URL and RELAY_URL, so it did not work on the novel list sort page.
How can I fix it?
Thanks for your helping!
