### ISSUE TITLE
Relay 是不是有異常狀況

### ISSUE THREAD

**Issue by SachiaLanlus** [MewX/light-novel-library_Wenku8_Android#118]
從今天開始打開 APP 就會跳出這個錯誤訊息。
目前只有在最近更新以及排行榜中的總點擊排行, 總推薦排行以及月點擊排行這三項會無法正常使用。

其中最近更新頁面是跳出這個訊息:
![Screenshot_2024-06-05-20-13-33-086_org mewx wenku8](https://github.com/MewX/light-novel-library_Wenku8_Android/assets/12500621/1fe9d374-7b2d-4757-b6d7-844b73ce5831)
排行榜中的三項則是空白的畫面，但沒有錯誤訊息。

**Comment by yappy2000d** [comment]
same question.

**Comment by SachiaLanlus** [comment]
今天就好了 應該是短暫抽風而已

**Comment by MewX** [comment]
谢谢反馈，好像是前阵子AWS抽风导致的。
