### ISSUE TITLE
请问是不维护了么？

### ISSUE THREAD

**Issue by eromoe** [MewX/light-novel-library_Wenku8_Android#12]
只能登陆，但是还是现实数据解析失败

PS： 想顺便问这个项目进展如何? https://prpr.mewx.org/

**Comment by MewX** [comment]
你好，请参考这个： #9  注册时间晚的会员和未登录的会员，服务器是不会返回数据的～

PRPR那个项目，谢谢关注，暂时没有动力去写了，版权打压太严重了
