### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by 1170626506** [MewX/light-novel-library_Wenku8_Android#124]
你好，今天下午app最近更新和排行榜功能突然无法使用，如附件所示，请问该如何解决，谢谢
![Screenshot_2024_0919_203532](https://github.com/user-attachments/assets/323ca6ce-3fc4-40f5-b6c0-179e03c770f3)

**Comment by SaberYoung666** [comment]
感觉可能是数据源的api挂了，因为轻小说文库的网站还能正常打开

**Comment by MewX** [comment]
应该已经恢复了？毕竟也不是我能控制的。
