### ISSUE TITLE
软件无法使用

### ISSUE THREAD

**Issue by Sorrakado** [MewX/light-novel-library_Wenku8_Android#126]
老是显示数据解析失败，我登录了也不行
用户名:kaga1i

**Comment by MewX** [comment]
不知道是不是因为加了cloudflare DDoS保护，所以有时候验证不通过

**Comment by aclgh** [comment]
![Screenshot_2024-11-26-01-35-56-364_org.mewx.wenku8.jpg](https://github.com/user-attachments/assets/f61fc2a4-a399-481f-bb21-2f719247916a)

无论是否登录，都会遇到同样的问题

**Comment by onlycatdoraemon** [comment]
最近我也遇到这个情况😱

**Comment by MewX** [comment]
检查了下，现在的中继服务请求数量还挺大的。直接爆了我的额度。。。

我把中继服务迁移到新的服务器了，我测试了下可以正常访问了，但是我的支出可能会变大。可能很快就不得不对中继服务进行收费了吧，大概。。。

**Comment by onlycatdoraemon** [comment]
如果需要捐赠的话我会出一份力的（加油！都晓得为爱发电的不容易）
