### ISSUE TITLE
章节处理

### ISSUE THREAD

**Issue by gaoyuan117** [MewX/light-novel-library_Wenku8_Android#15]
请问您是怎么把一整本书籍分章节的

**Comment by MewX** [comment]
数据本身就是分好章节的。

**Comment by gaoyuan117** [comment]
一本书完本了，下载下来是一个TXT文件，怎么分成一张一张的呢？您方便加下QQ好友吗1179074755，麻烦您了

**Comment by MewX** [comment]
抱歉不方便，所有请求都可以在API代码里面找到，毫无悬念的
