### ISSUE TITLE
app 架构太low了

### ISSUE THREAD

**Issue by hunter524** [MewX/light-novel-library_Wenku8_Android#2]
首先你可以猜一下我是谁。其次想要告诉你一个信息，现在的app采用Activity 和 Fragment的框架已经有点过时的感觉了。虽然Activity和Fragment是谷歌官方推荐的，但是由于种种生命周期无法控制的原因，多数商业化的app已经不再使用了。现在的app基本上只有一个主要的Activity。Square公司有一套框架不错，不过俺们至今未搞明白 。参见：https://github.com/bboyfeiyu/android-tech-frontier/tree/master/androidweekly/Square%20%E5%BC%80%E6%BA%90%E5%BA%93Flow%E5%92%8CMortar%E7%9A%84%E4%BB%8B%E7%BB%8D

**Comment by MewX** [comment]
\_(:3」∠)\_ 首先多谢指教！
第一次写安卓app嘛，java也是第一次用来写项目嘛，直接裸奔没用框架额。
php目前正在学习laravel，安卓方面框架还真没在意过，看来要了解了解了，还有什么建议欢迎继续提~各方面都可以~

**Comment by hunter524** [comment]
小夏啊。。。

**Comment by MewX** [comment]
:laughing: 涛涛？

**Comment by hunter524** [comment]
哦？这个关了啊！
