### ISSUE TITLE
关于设计上的一些改进

### ISSUE THREAD

**Issue by fython** [MewX/light-novel-library_Wenku8_Android#3]
看到这款应用觉得很棒，界面都有用心地按照 Material Design 设计规范做。
但有些界面还可以更好的改进，比如卡片的使用：
Material Design 设计规范中提到一些场合不应该使用卡片，尤其是一些固定高度的 List 项，在这款 app 中的搜索历史、小说章节选择直接使用平面 List 效果可能会更好。

正好昨天刚发了一篇关于 CardView 的文章希望能帮到一点小忙：http://blog.feng.moe/2015/10/24/something-about-cardview-development/

**Comment by Ivolian** [comment]
这个说明真心长。。。

**Comment by fython** [comment]
链接里面的是文章，写了 CardView 各个方面的使用技巧，当然长啊。

**Comment by MewX** [comment]
@fython 感谢！ _(:3」∠)_ 之前做的时候我仔细看了谷歌的规范了，比如章节列表就不推荐用，然后看到设计师ZERO做出来的图效果还不错，整个页面是一个整体，于是就采用card了。如果采用list，那么上面的小说信息和章节要采用分层展示了 _(:3」∠)_ 搜索历史记录可能改掉确实要好些
谢谢提建议，以后新app会注意的。wenku新的app快出来了，所以本app不会大改了~

**Comment by fython** [comment]
@MewX 嘿嘿，不要紧ww
