### ISSUE TITLE
点击最新章节可以直接跳转到阅读器

### ISSUE THREAD

**Issue by MewX** [MewX/light-novel-library_Wenku8_Android#30]
![image](https://user-images.githubusercontent.com/5752560/42553060-ceb2644e-8511-11e8-8e7a-2144e0d7a644.png)

**Comment by taiyonghai** [comment]
I  fuck your  family,I say I don’t know who are you again! Please stop!

发送自 Windows 10 版邮件应用

发件人: Yuanzhong Xia
发送时间: 2018年7月11日 13:53
收件人: MewX/light-novel-library_Wenku8_Android
抄送: Subscribed
主题: [MewX/light-novel-library_Wenku8_Android] 点击最新章节可以直接跳转到阅读器 (#30)
