### ISSUE TITLE
写得很用心，鄙人先收下了

### ISSUE THREAD

**Issue by ghkjgod** [MewX/light-novel-library_Wenku8_Android#4]
我准备在你这个APP的基础改进一下，正好我这里有个服务器，准备用服务器代理的形式重新整一个，现在好用的轻小说应用不多了，两年前我为天使轻小说写过一个，到最后还是断了。
感觉做得很用心，我现在正在用fresco和okhttp等重写一些基础部分，过时函数和一些组件都会重新做一下，服务器部分我也会用心的写一个。
非常感谢，我是个懒人，很多交互和切图布局都觉得非常麻烦，就一直没怎么用心（因为我特么的就是写后端的……）
有了您这个开源项目，我觉得非常幸运。

如果做完了，APP会保留你的信息

**Comment by MewX** [comment]
\_(:3」∠)\_ 嘛，开源的目的也就是为了促进百花齐放~

所以欢迎二次开发！完成的时候再来这边和我打声招呼吧~

对了，开源协议是`GPL v2`（=。= 实在想无视，我就睁只眼闭只眼了）
