### ISSUE TITLE
Adding HTTP insecure request support for Android 9.0

### ISSUE THREAD

**Issue by liweichen6** [MewX/light-novel-library_Wenku8_Android#41]
实机 (OnePlus 6) 升级至 Android 9.0 后登陆失效，点击头像提示 "Relogged." 但无任何反应。
清除数据后可以进入登陆界面，但点击登陆无任何提示，尝试抓了下包没有看到任何发送请求。
虚机 (Studio 自带 AVD，Pixel 2 Android 9.0 Google Play) 复现了同样的结果。

水平有限没有找到原因，[9.0 变化里提到 ”移除了 Apache HTTP“](https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p)，但看了下 app 用的 HttpURLConnection 应该没有影响。

**Comment by ciskonc** [comment]
我也有这个情况

**Comment by fython** [comment]
可能是 9.0 默认限制了明文 HTTP 连接

**Comment by MewX** [comment]
@fython 这么一说还是很有可能的，这个项目里面用的一个volley网络库实现是用的org.apache.http.*

感谢反馈！

**Comment by MewX** [comment]
机缘巧合检查了下volley，还在维护，应该可以排除是volley的问题。

然后搜索了一下类似的问题可能是由于wenku8到目前为止一直不支持https的连接。所以我之后会妥协一下加个允许http请求的参数：https://stackoverflow.com/a/50834600/4206925

**Comment by MewX** [comment]
已修复：https://github.com/MewX/light-novel-library_Wenku8_Android/releases/tag/v1.6
