### ISSUE TITLE
通过解析HTML获取最近更新和排行榜的可行性？

### ISSUE THREAD

**Issue by tinyAdapter** [MewX/light-novel-library_Wenku8_Android#44]
看了 #9 ，知道情况了，但是就wenku8这个网站的样子……应该是从开站之初就没改过前端吧emmm

所以说能否通过直接访问网站，解析HTML内容来获取最近更新和排行榜呢？

当然了，如果wenku8那边不认可这种做法的话，就当我没说过好了 🤣

**Comment by MewX** [comment]
网站不是我管理的所以我没办法添加新功能。本来我也是想这个思路的，但是我调试了一下，网站和app用的是不同的session，所以可能会稍微麻烦点，如果愿意的话欢迎提交pr:smile:

**Comment by MewX** [comment]
还是关了，没必要折腾 =。=
