### ISSUE TITLE
接口过期

### ISSUE THREAD

**Issue by notOnly20k** [MewX/light-novel-library_Wenku8_Android#48]
请问接口是废弃掉了吗？请求下来的只有数字

**Comment by MewX** [comment]
哪个接口？

**Comment by notOnly20k** [comment]
感谢回复
打开app后提示数据解析失败；
控制台打印org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT 4@1:2 in java.io.StringReader@e0d3b63) 
getNovelListWithInfo方法解析失败，我打印下返回的xml都是4

**Comment by MewX** [comment]
哦哦，这个是版权原因，未登陆的不显示列表的。

详情参考这里的错误定义：https://github.com/MewX/light-novel-library_Wenku8_Android/blob/master/studio-android/LightNovelLibrary/app/src/main/java/org/mewx/wenku8/global/api/Wenku8API.java#L209-L254

**Comment by MewX** [comment]
哦对了，你可以从搜索页面查找你需要的

**Comment by notOnly20k** [comment]
你好我登录后还是显示一样的错误。。。搜索是可以用的但是排行榜和最近更新都没有数据。。。

**Comment by MewX** [comment]
因为版权原因，新用户不开放这些东西

**Comment by notOnly20k** [comment]
哦哦好的，非常感谢
