### ISSUE TITLE
大神，找到了，是在这里吧

### ISSUE THREAD

**Issue by lijingyuan30** [MewX/light-novel-library_Wenku8_Android#5]
弄了两天了，各种百度，有时候报的错还不一样

**Comment by lijingyuan30** [comment]
刚开始是翻墙的问题，现在没有翻墙的问题了，都可以直接更新，现在报的错是Grade DSL method  not found  useLibrary()

**Comment by lijingyuan30** [comment]
大神大神，您能提供下您的环境吗，我照着您那版本弄，看看，

**Comment by MewX** [comment]
我的是Android Studio 2.0 Preview2。
这个错误应该是Gradle版本问题，参考这个吧：http://stackoverflow.com/questions/32779865/gradle-dsl-method-not-found-uselibrary

**Comment by lijingyuan30** [comment]
下班啦啊

**Comment by lijingyuan30** [comment]
那个页面我搜到过，上面意思是改成1.3.0？。。。

**Comment by lijingyuan30** [comment]
还是整不好，唉，不整了。谢谢您的回复，打扰啦，祝您生活愉快

**Comment by MewX** [comment]
好吧。。。
