### ISSUE TITLE
阅读界面

### ISSUE THREAD

**Issue by wuyinlei** [MewX/light-novel-library_Wenku8_Android#6]
楼主，问下，这个阅读英文的时候，在一行显示不全的时候，是英文单词被断开了还是向那种流式布局那样进行空格填充呢

**Comment by MewX** [comment]
当前版本是断词的，就是那种怎样简单怎样实现XD
Project PRPR就会是自动增加间距填充~

**Comment by wuyinlei** [comment]
谢谢回复哈，期待您的大作
