### ISSUE TITLE
无法读取内部存储

### ISSUE THREAD

**Issue by tasm07** [MewX/light-novel-library_Wenku8_Android#65]
设置—侧栏壁纸—选择自定义的图片，获取的根目录为空
Android 版本 :10
App 版本 :1.11
已授予存储权限
格式化了存储卡做为内部存储
（以及，新版本是不是修改了存储逻辑？似乎不需要 wneku8 文件夹也可以正常运行）
最后，感谢您的辛勤付出🙏

**Comment by MewX** [comment]
oh！可能是三方库的bug，我明天在测试机上看下，谢谢反馈！

**Comment by tasm07** [comment]
还有一点不知道是不是玄学问题，就是内部存储中有 wenku8 数据目录的时候无法加载图片，然后重启 App 后登录失效；但是删掉这个目录就正常了
（我用 Root 看了下 /data 分区，里面有和原先目录中一样的文件，似乎数据目录被迁移到了应用数据里）

**Comment by MewX** [comment]
这个bug应该是Android 10 特有的 (下图Android 6/10/11):
![image](https://user-images.githubusercontent.com/5752560/92338610-d259ac00-f0f4-11ea-93c9-8455bef75e8e.png)

wenku8目录消失应该是因为这个改动 https://developer.android.com/preview/privacy/storage

加上这个flag倒是可以正常生成wenku8目录和浏览文件了.

浏览文件还有个bug, 返回上级目录就回不到storage目录下面了... 三方库的bug

**Comment by MewX** [comment]
看了下umeng统计数据, 4.4- 的用户还有5%左右, 还是得保留兼容性.

估计有空的时候把4.4+部分改成系统FilePicker.

**Comment by MewX** [comment]
v1.12 修复了图片选择这部分. 剩下的交给 #67 处理, 先关了哈. 有其他comment可以继续留言
