### ISSUE TITLE
点搜索也是崩溃。。。

### ISSUE THREAD

**Issue by rtyheji** [MewX/light-novel-library_Wenku8_Android#8]

**Comment by MewX** [comment]
哈？麻烦把异常栈发一下

**Comment by rtyheji** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mewx.wenku8/org.mewx.wenku8.activity.SearchActivity}: android.view.InflateException: Binary XML file line #70: Error inflating class ImageView
03-03 09:14:19.411 10566-10566/org.mewx.wenku8 E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
03-03 09:14:19.411 10566-10566/org.mewx.wenku8 E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
03-03 09:14:19.411 10566-10566/org.mewx.wenku8 E/AndroidRuntime:     at android.app.ActivityThread.access$1100(ActivityThread.java:141)
03-03 09:14:19.411 10566-10566/org.mewx.wenku8 E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
03-03 09:14:19.411 10566-10566/org.mewx.wenku8 E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-03 09:14:19.411 10566-10566/org.mewx.wenku8 E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
03-03 09:14:19.411 10566-10566/org.mewx.wenku8 E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5333)

**Comment by MewX** [comment]
你的系统是4.x吗？
有可能是系统未定义toolbar_search.xml 76行的图形的原因。

**Comment by rtyheji** [comment]
我用的是4.4的。。

**Comment by MewX** [comment]
4.4的话，麻烦下载1.3.1使用吧：https://github.com/MewX/light-novel-library_Wenku8_Android/releases/tag/v1.3.1
