### ISSUE TITLE
选择我的收藏时会闪退

### ISSUE THREAD

**Issue by andla119** [MewX/light-novel-library_Wenku8_Android#85]
选择我的收藏时，会先显示  正在同步书架 然后会闪退。选择取消同步书架后大概半秒也会闪退。如果挂代理好像就没有问题。鸿蒙和emui9都有这个问题，是最近一两月才出现的问题，之前就算是鸿蒙也没有问题

**Comment by MewX** [comment]
收到，谢谢反馈。环境变量有点多，目前需要排查
- 是否是网络问题
- 是否是服务器问题
- 是否是鸿蒙/emui9的问题（据我所知这俩是一样的）

我留意下bug报告。

**Comment by andla119** [comment]
Emui9上次更新还是上半年，鸿蒙我手上的最近没更新过，我认为可能是网站或者网络问题。现在挂代理也有问题，闪退的瞬间回到最近更新（也有可能是闪退瞬间重新打开了软件）

**Comment by andla119** [comment]
收藏里有本书删了就好了

**Comment by MewX** [comment]
nice 谢谢反馈
