### ISSUE TITLE
关于下载

### ISSUE THREAD

**Issue by whghjyh** [MewX/light-novel-library_Wenku8_Android#89]
我想知道可否有抓取并下载打包成epub的功能，不是计算机从业人员，不知道技术上是不是可以实现。（本地缓存下载在文件夹内全都是分段文件）我是希望可以通过此软件下载，在本地的阅读器内阅读。
  最后，感谢作者对此软件的开发

**Comment by MewX** [comment]
谢谢反馈，技术上可行，但是app本身不是下载器，所以不会提供打包成epub的功能。另外，数据源只有纯文本的信息，所以可以直接去网站上下载txt打包文本。

**Comment by whghjyh** [comment]
好的，多谢回复
