### ISSUE TITLE
服务器抽风？

### ISSUE THREAD

**Issue by davidtaysnow88** [MewX/light-novel-library_Wenku8_Android#9]
最近更新和排行榜用不了
一直显示数据解析失败。

**Comment by MewX** [comment]
注册时间晚的会员和未登录的会员，服务器是不会返回数据的～

**Comment by woeijiunn88** [comment]
哦哦 知道了

**Comment by wuchenkang** [comment]
请问这个的机制是注册时间点晚于某一时刻就不返回数据了还是注册之后满多少天就能够返回数据？ @MewX

**Comment by MewX** [comment]
@wuchenkang `user_id > X` 的用户均不返回数据
