### ISSUE TITLE
服务器寄了？

### ISSUE THREAD

**Issue by qwq233** [MewX/light-novel-library_Wenku8_Android#91]
服务器寄了？
![image](https://user-images.githubusercontent.com/20317838/158063038-aba89adf-47b2-4aee-9f81-6a35c8d58ad7.png)

**Comment by MewX** [comment]
ERR_HTTP2_PROTOCOL_ERROR looks like a setup issue from your side.

**Comment by qwq233** [comment]
> Works for me though. ERR_HTTP2_PROTOCOL_ERROR looks like a setup issue from your side.

唔 好吧 可能我梯子寄了 我扔不代理列表试试
