### ISSUE TITLE
app缓存目录是哪

### ISSUE THREAD

**Issue by soft52013** [MewX/light-novel-library_Wenku8_Android#95]
想用别的阅读器打开，但找不到文件和缓存目录

**Comment by MewX** [comment]
`storage/wenku8`

别的阅读器打不开的，因为不是标准的小说格式，可以参考这个 https://github.com/MewX/light-novel-library_Wenku8_Android/releases/tag/save-sample-v1.2

**Comment by soft52013** [comment]
> `storage/wenku8`
> 
> 别的阅读器打不开的，因为不是标准的小说格式，可以参考这个 https://github.com/MewX/light-novel-library_Wenku8_Android/releases/tag/save-sample-v1.2

感谢
